spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://careerup.c2pjf92fzjv5.ap-northeast-2.rds.amazonaws.com:3306/mydb
    username: root
    #insert password
    password: 12345678

  jpa:
    properties:
      hibernate:
        show-sql: "true"
        format_sql: "true"
    hibernate:
      ddl-auto: update
